apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80        # External port to expose
      targetPort: 5000 # Port your Flask app listens on
  type: LoadBalancer   # Expose the service to the internet
